version: '3'

services:
  basic:
    build: .
    ports:
      - 8081:80
    volumes:
      - ./basic:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
      - ./basic/cachegrind:/tmp/xdebug