version: '3'

services:
  basic:
    build: ./docker/php-xdebug
    ports:
      - 8081:80
    volumes:
      - ./basic:/var/www/html
      - ./docker/php-xdebug/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
      - ./basic/cachegrind:/tmp/xdebug

  slow-composer:
    build: ./docker/php-xdebug
    ports:
      - 8082:80
    volumes:
      - ./slow-composer:/var/www/html
      - ./docker/php-xdebug/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
      - ./docker/php-xdebug/default.conf:/etc/apache2/sites-available/000-default.conf
      - ./slow-composer/cachegrind:/tmp/xdebug
  
  slow-database:
    build: ./docker/slow-db
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: xdebug_teste
      MYSQL_USER: xdebug_teste
      MYSQL_PASSWORD: xdebug_teste
      MYSQL_ROOT_PASSWORD: xdebug_teste
    cap_add: 
      - NET_ADMIN

  slow-wordpress:
    build: ./docker/php-xdebug
    ports:
      - 8083:80
    links:
      - slow-database:db
    volumes:
      - ./wordpress:/var/www/html
      - ./docker/php-xdebug/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
      - ./wordpress/cachegrind:/tmp/xdebug

  meminfo:
    build: ./docker/meminfo
    ports:
      - 8084:80
    volumes:
      - ./meminfo:/app
